title: "Kubernetes & Container Orchestration"
author: "Aaron González, Mathew Carballo, Daniel Porras"
lang: en
toc: true
lof: true
documentclass: IEEEtran
classoption:
  - 10pt
  - journal
  - compsoc
abstract: |
  TODO: un abstract
keywords: Kubernetes, Container Orchestration, Edge, Edge Computing
